<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Laravel\Passport\HasApiTokens;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Pharmacy extends Authenticatable
{
    use SoftDeletes, HasApiTokens;

    protected $appends = ['city_name'];

    protected $fillable = [
        'name',
        'email',
        'password',
        'phone',
        'city_id',
        'location',
        'location_link',
        'location_longitude',
        'location_latitude',
        'owner_name',
        'owner_phone',
        'license',
        'license_expire_at',
    ];

    /** @noinspection PhpUnused */
    public function getLicenseAttribute($value)
    {
        return $value ? \env('APP_URL') . '/storage/' . $value : null;
    }


    /** @noinspection PhpUnused */
    public function getCityNameAttribute()
    {
        $cityName = $this->City?->name;
        if ($this->relationLoaded('City')) {
            $this->unsetRelation('City');
        }
        return $cityName;
    }


    protected $hidden = [
        'password',
        'email',
        'updated_at',
        'deleted_at',
    ];

    protected $casts = [
        'password' => 'hashed',
    ];

    public function City(): BelongsTo
    {
        return $this->belongsTo(City::class, 'city_id');
    }

    public function RecipeMedicines(): HasMany
    {
        return $this->hasMany(RecipeMedicine::class, 'pharmacy_id');
    }

    public function PharmacyRequests(): HasMany
    {
        return $this->hasMany(PharmacyRequest::class, 'pharmacy_id');
    }

    public function toArray()
    {
        $routeName = request()->route()->getName();
        if ($routeName === 'GetPharmaciesUser') {
            $this->makeHidden(['owner_name', 'owner_phone', 'license', 'license_expire_at', 'created_at']);
        }
        return parent::toArray(); // TODO: Change the autogenerated stub
    }
}
